info:
  version: 0.1.0
  description: Library application

server:
  servlet:
    jsp:
      registered: false
  tomcat:
    max-connections: 1000
    threads:
      max: 30
      max-queue-capacity: 1000
    basedir: tomcat
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  compression:
    enabled: true
    min-response-size: 512
    mime-types: text/html,text/xml,text/plain,text/css,application/json
  ssl:
    enabled: false
  http2:
    enabled: true
  shutdown: immediate

spring:
  docker:
    compose:
      lifecycle-management: none
      enabled: false
  sql:
    init:
      mode: never
  application:
    name: library
    group: xpinjection
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    constructor-detector: use_delegating
  freemarker:
    enabled: true
    cache: true
    suffix: .ftl
  datasource:
    url: # define PostgreSQL DB URL
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: library-db-cp
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  web:
    resources:
      static-locations: classpath:/static/, classpath:/api/spec/
  jmx:
    enabled: false
  cache:
    type: simple
    cache-names: booksByAuthor

library:
  size: 0

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  predicate:
    exclude:
      - path: /admin/**
  format:
    style: http
  strategy: body-only-if-status-at-least
  minimum-status: 200

springdoc:
  packages-to-scan: com.xpinjection.library.adaptors.api
  swagger-ui:
    urls:
      - url: /v1/library-api.yaml
        name: static
      - url: /v3/api-docs.yaml
        name: generated

management:
  tracing:
    enabled: false
  endpoints:
    access:
      default: none